name: push
run-name: ${{ github.actor }} push test
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    outputs: 
      all: ${{ steps.changes.outputs.all}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      # - name: Get file changes
      #   id: get_file_changes
      #   uses: trilom/file-changes-action@v1.2.4
      #   with:
      #     output: " "
      # - name: Echo file changes
      #   run: | 
      #     echo Added: ${{ steps.get_file_changes.outputs.files_added }}
      #     echo Changed: ${{ steps.get_file_changes.outputs.files_modified }}
      #     echo Removed: ${{ steps.get_file_changes.outputs.files_removed }}
      - name: File changes
        id: changes
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"          
      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend
      - name: Start
        run: npm run build
        working-directory: ./frontend
