name: push
run-name: ${{ github.actor }} push test
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v1
        with: 
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Changed files
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "
      - name: Echo file changes
        run: |
        echo Added files: ${{ steps.get_file_changes.outputs.files_added }}
        echo Changed files: ${{ steps.get_file_changes.outputs.files_modified }}
        echo Removed files: ${{ steps.get_file_changes.outputs.files_removed }}
        working-directory: ./frontend
      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend
      - name: Start
        run: npm run build
        working-directory: ./frontend
